apiVersion: v1
kind: Secret
metadata:
  name: credpay-db
  namespace: credpay
  labels:
    app.kubernetes.io/part-of: credpay
  type: Opaque
  springData:
  DB_PASSWORD: "replace_me"
  spring.datasource.password: "replace_me"