# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

variables:
  acrserviceconnection: 'acr_serviceconnection'
  frontendrepository: 'credpay/frontend'
  userrepository: 'credpay/user-service'
  paymentrepository: 'credpay/payment-service'
  tag: '$(Build.BuildId)'
stages:
  - stage: dockerbuild
    displayName: docker build
    jobs:
      - job: buildpushimages
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'acr_serviceconnection'
              repository: '$(frontendrepository)'
              command: 'buildAndPush'
              Dockerfile: 'frontend-react/dockerfile'
              buildContext: 'frontend-react'
              tags: |
                $(tag)
                latest
          
          - task: Docker@2
            inputs:
              containerRegistry: 'acr_serviceconnection'
              repository: 'userrepository'
              command: 'buildAndPush'
              Dockerfile: 'user-service/dockerfile'
              buildContext: 'user-service'
              tags: |
                $(tag)
                latest
          - task: Docker@2
            inputs:
              containerRegistry: 'acr_serviceconnection'
              repository: 'paymentrepository'
              command: 'buildAndPush'
              Dockerfile: 'payment-service/dockerfile'
              buildContext: 'payment-service'
              tags: |
                $(tag)
                latest